settings:
  title: '一刀斩の小窝 - 全站状态监控'
  url: 'https://status.yidaozhan.top/' # used for Slack messages
  logo: tudou.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: '网站一切正常！'
  notAllmonitorsOperational: '网站部分炸服 ...'
  monitorLabelOperational: '网站可以访问'
  monitorLabelNotOperational: '网站炸了！'
  monitorLabelNoData: '无数据'
  dayInHistogramNoData: '无数据'
  dayInHistogramOperational: '一切正常'
  dayInHistogramNotOperational: ' 次炸服' # xx incident(s) recorded

monitors:
  - id: blog
    name: '博客 (blog.yidaozhan.top)'
    description: '我的个人博客 (Vercel)'
    url: 'https://blog.yidaozhan.top/'
    method: GET
    followRedirect: true
    linkable: false

  - id: alist
    name: '文件分享 (file.yidaozhan.top)'
    description: '文件分享站 (Alist / 阿里云盘 / OneDrive)'
    url: 'https://file.yidaozhan.top/'
    method: GET
    followRedirect: true
    linkable: false
    
  - id: om
    name: '文件分享 2 (pan.yidaozhan.top)'
    description: '文件分享站 (OneManager)'
    url: 'https://pan.yidaozhan.top/'
    method: GET
    followRedirect: true
    linkable: false
    
  - id: analytics
    name: '访问量统计 (analytics.yidaozhan.top)'
    description: '访问量统计 (Umami)'
    url: 'https://analytics.yidaozhan.top/'
    method: GET
    followRedirect: true
    linkable: false

  - id: qexo
    name: '博客后台面板'
    description: '博客后台面板 (Qexo)'
    url: 'https://qexo.yidaozhan.top/'
    method: GET
    followRedirect: true
    linkable: false
   
  - id: az1
    name: 'QQ 机器人'
    description: '群内 QQ 机器人 (日本东京微软云)'
    url: 'https://azure.yidaozhan.ga/'
    method: GET
    followRedirect: true
    linkable: false
