settings:
  title: '一刀斩の小窝 - 全站状态监控'
  url: 'https://status.yidaozhan.top/' # used for Slack messages
  logo: tudou.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: '网站一切正常！'
  notAllmonitorsOperational: '网站部分炸服 ...'
  monitorLabelOperational: '网站可以访问'
  monitorLabelNotOperational: '网站炸了！'
  monitorLabelNoData: '无数据'
  dayInHistogramNoData: '无数据'
  dayInHistogramOperational: '一切正常'
  dayInHistogramNotOperational: ' 次炸服' # xx incident(s) recorded

monitors:
  - id: blog
    name: '博客 (blog.yidaozhan.top)'
    description: '我的个人博客 (Vercel)'
    url: 'https://blog.yidaozhan.top/'
    method: GET
    followRedirect: true
    linkable: false

  - id: alist
    name: '文件分享 (file.yidaozhan.top)'
    description: '文件分享站 (Alist / 阿里云盘 / OneDrive)'
    url: 'https://file.yidaozhan.top/'
    method: GET
    followRedirect: true
    linkable: false
    
  - id: om
    name: '文件分享 2 (pan.yidaozhan.top)'
    description: '文件分享站 (OneManager)'
    url: 'https://pan.yidaozhan.top/od_e5/'
    method: GET
    followRedirect: true
    linkable: false
    
  - id: az1
    name: 'QQ 机器人'
    description: '群内 QQ 机器人 (日本东京微软云，和文件分享在同一台服务器)'
    url: 'http://azure2.yidaozhan.ga/'
    method: GET
    followRedirect: true
    linkable: false
    
  - id: enginetribe
    name: '引擎部落 (enginetribe.gq)'
    description: 'SMM:WE 全球关卡重新实现'
    url: 'http://enginetribe.gq:25019/'
    method: GET
    followRedirect: true
    linkable: true
