settings:
  title: '一刀斩の小窝 - 全站状态监控'
  url: 'https://status.yidaozhan.top/' # used for Slack messages
  logo: tudou.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: '网站一切正常！'
  notAllmonitorsOperational: '网站部分不可用 ...'
  monitorLabelOperational: '网站可以访问'
  monitorLabelNotOperational: '网站炸了！'
  monitorLabelNoData: '无数据'
  dayInHistogramNoData: '无数据'
  dayInHistogramOperational: '一切正常'
  dayInHistogramNotOperational: ' 次事故' # xx incident(s) recorded

monitors:
  - id: blog
    name: '博客'
    description: '我的个人博客'
    url: 'https://blog.yidaozhan.top/'
    method: GET
    followRedirect: true
    linkable: true

  - id: alist
    name: '文件分享'
    description: '文件分享站 (AList / OneDrive)'
    url: 'https://file.yidaozhan.top/'
    method: GET
    followRedirect: true
    linkable: true
    
  #- id: az1
#    name: 'QQ 机器人'
#    description: '群内 QQ 机器人 (日本东京微软云，和文件分享在同一台服务器)'
#    url: 'http://azure2.yidaozhan.ga/'
#    method: GET
#    followRedirect: true
#    linkable: false
    
    
#  - id: enginetribestroage
#    name: '引擎部落关卡存储'
#    description: '基于 OneManager'
#    url: 'https://storage-v2.enginetribe.gq/'
#    method: GET
#    followRedirect: true
#    linkable: false
